package com.example.util

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val nativeName: String,
    val flagEmoji: String
) {
    ENGLISH("en", "English", "English", "🇺🇸"),
    HINDI("hi", "Hindi", "हिंदी", "🇮🇳"),
    SPANISH("es", "Spanish", "Español", "🇪🇸"),
    BENGALI("bn", "Bengali", "বাংলা", "🇮🇳"),
    FRENCH("fr", "French", "Français", "🇫🇷"),
    TELUGU("te", "Telugu", "తెలుగు", "🇮🇳"),
    MARATHI("mr", "Marathi", "मराठी", "🇮🇳"),
    TAMIL("ta", "Tamil", "தமிழ்", "🇮🇳");

    companion object {
        fun fromCode(code: String): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: ENGLISH
        }
    }
}

data class LocalizedStrings(
    val appTitle: String,
    val appSubtitle: String,
    val oneTapHelp: String,
    val tapToTriggerSos: String,
    val emergencyActive: String,
    val resolveSos: String,
    val emergencySiren: String,
    val sirenActive: String,
    val testSilentSos: String,
    val liveGpsActive: String,
    val gpsStandby: String,
    val instantSharedBanner: String,
    val daisyChainTitle: String,
    val daisyChainSubtitle: String,
    val startChain: String,
    val cycle: String,
    val answeredConnected: String,
    val escalateNext: String,
    val oneMinAudioTitle: String,
    val audioRecording: String,
    val analyzeNow: String,
    val aiSituationTitle: String,
    val aiAssistantTab: String,
    val askAssistantPlaceholder: String,
    val sendQuery: String,
    val dashboardTab: String,
    val sosTab: String,
    val contactsTab: String,
    val profileTab: String,
    val selectLanguage: String,
    val themeMode: String,
    val lightTheme: String,
    val darkTheme: String,
    val primaryContact: String,
    val policeEmergency: String,
    val mapDirections: String,
    val callDirectly: String
)

object AppLocalization {
    fun getStrings(language: AppLanguage): LocalizedStrings {
        return when (language) {
            AppLanguage.HINDI -> LocalizedStrings(
                appTitle = "हरशील्ड (HerShield)",
                appSubtitle = "एआई संचालित महिला सुरक्षा और आपातकालीन एसओएस",
                oneTapHelp = "एक टैप में मदद",
                tapToTriggerSos = "एसओएस भेजने के लिए टैप करें",
                emergencyActive = "आपातकाल सक्रिय",
                resolveSos = "मैं सुरक्षित हूँ (अलर्ट बंद करें)",
                emergencySiren = "आपातकालीन सायरन",
                sirenActive = "सायरन बज रहा है",
                testSilentSos = "साइलेंट एसओएस",
                liveGpsActive = "रीयल-टाइम जीपीएस ट्रैकिंग चालू",
                gpsStandby = "जीपीएस तैयार",
                instantSharedBanner = "प्राथमिक संपर्क को गूगल मैप्स लाइव लोकेशन तुरंत भेज दी गई!",
                daisyChainTitle = "ऑटो कॉलिंग डेज़ी चेन",
                daisyChainSubtitle = "जब तक कोई उत्तर न दे, क्रमबद्ध रूप से कॉल करें",
                startChain = "कॉलिंग शुरू करें",
                cycle = "चक्र",
                answeredConnected = "उत्तर दिया गया",
                escalateNext = "अगले को कॉल करें",
                oneMinAudioTitle = "1-मिनट ऑडियो सुरक्षा रिकॉर्डिंग",
                audioRecording = "ऑडियो रिकॉर्ड हो रहा है...",
                analyzeNow = "अभी विश्लेषण करें",
                aiSituationTitle = "एआई सुरक्षा स्थिति विश्लेषक",
                aiAssistantTab = "एस्ट्रा एआई सहायक",
                askAssistantPlaceholder = "सुरक्षा से जुड़ा कोई भी प्रश्न पूछें...",
                sendQuery = "पूछें",
                dashboardTab = "डैशबोर्ड",
                sosTab = "एसओएस",
                contactsTab = "संपर्क",
                profileTab = "प्रोफ़ाइल",
                selectLanguage = "भाषा चुनें",
                themeMode = "थीम बदलें",
                lightTheme = "लाइट थीम",
                darkTheme = "डार्क थीम",
                primaryContact = "प्राथमिक संपर्क",
                policeEmergency = "पुलिस हेल्पलाइन (112)",
                mapDirections = "गूगल मैप्स पर देखें",
                callDirectly = "सीधा कॉल करें"
            )

            AppLanguage.SPANISH -> LocalizedStrings(
                appTitle = "HerShield",
                appSubtitle = "Seguridad femenina impulsada por IA y SOS instantáneo",
                oneTapHelp = "Ayuda de un toque",
                tapToTriggerSos = "Toca para activar SOS",
                emergencyActive = "EMERGENCIA ACTIVA",
                resolveSos = "Estoy a salvo (Cancelar alerta)",
                emergencySiren = "Sirena de emergencia",
                sirenActive = "Sirena activa",
                testSilentSos = "SOS silencioso",
                liveGpsActive = "SEGUIMIENTO GPS EN TIEMPO REAL ACTIVO",
                gpsStandby = "GPS en espera",
                instantSharedBanner = "¡Ubicación de Google Maps compartida al instante con el contacto principal!",
                daisyChainTitle = "Cadena de llamadas de emergencia",
                daisyChainSubtitle = "Llamadas secuenciales hasta que alguien conteste",
                startChain = "Iniciar cadena",
                cycle = "Ciclo",
                answeredConnected = "Contestada",
                escalateNext = "Llamar siguiente",
                oneMinAudioTitle = "Grabación de seguridad de 1 minuto",
                audioRecording = "Grabando audio...",
                analyzeNow = "Analizar ahora",
                aiSituationTitle = "Evaluador de amenazas por IA",
                aiAssistantTab = "Asistente IA Astra",
                askAssistantPlaceholder = "Pregunta sobre tu seguridad...",
                sendQuery = "Enviar",
                dashboardTab = "Panel",
                sosTab = "SOS",
                contactsTab = "Contactos",
                profileTab = "Perfil",
                selectLanguage = "Seleccionar idioma",
                themeMode = "Tema de la aplicación",
                lightTheme = "Tema claro",
                darkTheme = "Tema oscuro",
                primaryContact = "Contacto principal",
                policeEmergency = "Policía (112)",
                mapDirections = "Abrir Google Maps",
                callDirectly = "Llamar directo"
            )

            AppLanguage.BENGALI -> LocalizedStrings(
                appTitle = "হারশিল্ড (HerShield)",
                appSubtitle = "এআই চালিত নারী সুরক্ষা ও জরুরি এসওএস",
                oneTapHelp = "এক ট্যাপে সাহায্য",
                tapToTriggerSos = "এসওএস পাঠাতে ট্যাপ করুন",
                emergencyActive = "জরুরি অবস্থা সক্রিয়",
                resolveSos = "আমি নিরাপদ (অ্যালার্ট বাতিল)",
                emergencySiren = "জরুরি সাইরেন",
                sirenActive = "সাইরেন বাজছে",
                testSilentSos = "নীরব এসওএস",
                liveGpsActive = "রিয়েল-টাইম জিপিএস ট্র্যাকিং সক্রিয়",
                gpsStandby = "জিপিএস প্রস্তুত",
                instantSharedBanner = "প্রধান পরিচিতির কাছে সরাসরি গুগল ম্যাপস লোকেশন পাঠানো হয়েছে!",
                daisyChainTitle = "জরুরি কলিং চেইন",
                daisyChainSubtitle = "উত্তর না পাওয়া পর্যন্ত পর্যায়ক্রমে কল",
                startChain = "কলিং শুরু করুন",
                cycle = "চক্র",
                answeredConnected = "উত্তর দেওয়া হয়েছে",
                escalateNext = "পরবর্তী কল",
                oneMinAudioTitle = "১-মিনিট অডিও নিরাপত্তা রেকর্ডিং",
                audioRecording = "অডিও রেকর্ড হচ্ছে...",
                analyzeNow = "এখন বিশ্লেষণ করুন",
                aiSituationTitle = "এআই পরিস্থিতি বিশ্লেষক",
                aiAssistantTab = "অ্যাস্ট্রা এআই সহকারী",
                askAssistantPlaceholder = "সুরক্ষা বিষয়ে যেকোনো প্রশ্ন করুন...",
                sendQuery = "পাঠান",
                dashboardTab = "ড্যাশবোর্ড",
                sosTab = "এসওএস",
                contactsTab = "পরিচিতি",
                profileTab = "প্রোফাইল",
                selectLanguage = "ভাষা নির্বাচন করুন",
                themeMode = "থিম পরিবর্তন",
                lightTheme = "লাইট থিম",
                darkTheme = "ডার্ক থিম",
                primaryContact = "প্রধান পরিচিতি",
                policeEmergency = "পুলিশ হেল্পলাইন (১১২)",
                mapDirections = "গুগল ম্যাপে দেখুন",
                callDirectly = "সরাসরি কল করুন"
            )

            AppLanguage.FRENCH -> LocalizedStrings(
                appTitle = "HerShield",
                appSubtitle = "Sécurité féminine IA & SOS d'urgence",
                oneTapHelp = "Aide en un clic",
                tapToTriggerSos = "Appuyez pour déclencher le SOS",
                emergencyActive = "URGENCE ACTIVE",
                resolveSos = "Je suis en sécurité (Annuler)",
                emergencySiren = "Sirène d'urgence",
                sirenActive = "Sirène active",
                testSilentSos = "SOS silencieux",
                liveGpsActive = "SUIVI GPS EN TEMPS RÉEL ACTIF",
                gpsStandby = "GPS en attente",
                instantSharedBanner = "Position Google Maps partagée immédiatement avec le contact principal !",
                daisyChainTitle = "Chaîne d'appels d'urgence",
                daisyChainSubtitle = "Appels séquentiels jusqu'à réponse",
                startChain = "Lancer les appels",
                cycle = "Cycle",
                answeredConnected = "Connecté",
                escalateNext = "Appel suivant",
                oneMinAudioTitle = "Enregistrement de sécurité 1 min",
                audioRecording = "Enregistrement audio en cours...",
                analyzeNow = "Analyser maintenant",
                aiSituationTitle = "Évaluateur de situation IA",
                aiAssistantTab = "Assistant IA Astra",
                askAssistantPlaceholder = "Posez une question sur votre sécurité...",
                sendQuery = "Envoyer",
                dashboardTab = "Tableau de bord",
                sosTab = "SOS",
                contactsTab = "Contacts",
                profileTab = "Profil",
                selectLanguage = "Choisir la langue",
                themeMode = "Mode du thème",
                lightTheme = "Thème clair",
                darkTheme = "Thème sombre",
                primaryContact = "Contact principal",
                policeEmergency = "Police d'urgence (112)",
                mapDirections = "Ouvrir Google Maps",
                callDirectly = "Appeler directement"
            )

            AppLanguage.TELUGU -> LocalizedStrings(
                appTitle = "హర్‌షీల్డ్ (HerShield)",
                appSubtitle = "మహిళల రక్షణ & అత్యవసర ఎస్ఓఎస్",
                oneTapHelp = "ఒక్క ట్యాప్‌తో సహాయం",
                tapToTriggerSos = "ఎస్ఓఎస్ పంపడానికి నొక్కండి",
                emergencyActive = "అత్యవసర స్థితి ఆన్ చేయబడింది",
                resolveSos = "నేను సురక్షితంగా ఉన్నాను (ముగించు)",
                emergencySiren = "ఎమర్జెన్సీ సైరన్",
                sirenActive = "సైరన్ మోగుతోంది",
                testSilentSos = "సైలెంట్ ఎస్ఓఎస్",
                liveGpsActive = "రియల్ టైమ్ జీపీఎస్ ట్రాకింగ్ చురుకుగా ఉంది",
                gpsStandby = "జీపీఎస్ సిద్ధంగా ఉంది",
                instantSharedBanner = "ప్రధాన పరిచయానికి తక్షణమే గూగుల్ మ్యాప్స్ లొకేషన్ పంపబడింది!",
                daisyChainTitle = "ఎమర్జెన్సీ కాలింగ్ డెయిసీ చైన్",
                daisyChainSubtitle = "ఎవరైనా స్పందించే వరకు వరుస కాల్స్",
                startChain = "కాలింగ్ ప్రారంభించండి",
                cycle = "రౌండ్",
                answeredConnected = "మాట్లాడుతున్నారు",
                escalateNext = "తరువాతి వ్యక్తికి కాల్",
                oneMinAudioTitle = "1-నిమిషం ఆడియో భద్రతా రికార్డింగ్",
                audioRecording = "ఆడియో రికార్డ్ అవుతోంది...",
                analyzeNow = "ఇప్పుడే విశ్లేషించండి",
                aiSituationTitle = "ఏఐ భద్రతా పరిస్థితి విశ్లేషణ",
                aiAssistantTab = "ఆస్ట్రా ఏఐ సహాయకుడు",
                askAssistantPlaceholder = "భద్రత గురించి ఏదైనా అడగండి...",
                sendQuery = "పంపు",
                dashboardTab = "డ్యాష్‌బోర్డ్",
                sosTab = "ఎస్ఓఎస్",
                contactsTab = "కాంటాక్ట్స్",
                profileTab = "ప్రొఫైల్",
                selectLanguage = "భాషను ఎంచుకోండి",
                themeMode = "థీమ్ మార్పు",
                lightTheme = "లైట్ థీమ్",
                darkTheme = "డార్క్ థీమ్",
                primaryContact = "ప్రధాన సంప్రదింపు",
                policeEmergency = "పోలీస్ హెల్ప్‌లైన్ (112)",
                mapDirections = "గూగుల్ మ్యాప్స్ తెరవండి",
                callDirectly = "నేరుగా కాల్ చేయండి"
            )

            AppLanguage.MARATHI -> LocalizedStrings(
                appTitle = "हरशील्ड (HerShield)",
                appSubtitle = "महिला सुरक्षा आणि तात्काळ एसओएस",
                oneTapHelp = "एका टॅपमध्ये मदत",
                tapToTriggerSos = "एसओएस पाठवण्यासाठी टॅप करा",
                emergencyActive = "आणीबाणी सक्रिय",
                resolveSos = "मी सुरक्षित आहे (अलर्ट बंद करा)",
                emergencySiren = "आणीबाणी सायरन",
                sirenActive = "सायरन वाजत आहे",
                testSilentSos = "शांत एसओएस",
                liveGpsActive = "रिअल-टाइम जीपीएस ट्रॅकिंग सुरू",
                gpsStandby = "जीपीएस स्टँडबाय",
                instantSharedBanner = "मुख्य संपर्काला गुगल मॅप्स लाईव्ह लोकेशन त्वरित पाठवले!",
                daisyChainTitle = "ऑटो कॉलिंग डेझी चेन",
                daisyChainSubtitle = "कोणीतरी उत्तर देईपर्यंत क्रमाने कॉल करा",
                startChain = "कॉलिंग सुरू करा",
                cycle = "फेरी",
                answeredConnected = "उत्तर मिळाले",
                escalateNext = "पुढील व्यक्तीला कॉल",
                oneMinAudioTitle = "१-मिनिट ऑडिओ सुरक्षा रेकॉर्डिंग",
                audioRecording = "ऑडिओ रेकॉर्डिंग सुरू आहे...",
                analyzeNow = "आत्ता विश्लेषण करा",
                aiSituationTitle = "एआय धोका विश्लेषक",
                aiAssistantTab = "अ‍ॅस्ट्रा एआय सहाय्यक",
                askAssistantPlaceholder = "सुरक्षेविषयी कोणताही प्रश्न विचारा...",
                sendQuery = "विचारा",
                dashboardTab = "डॅशबोर्ड",
                sosTab = "एसओएस",
                contactsTab = "संपर्क",
                profileTab = "प्रोफाइल",
                selectLanguage = "भाषा निवडा",
                themeMode = "थीम बदला",
                lightTheme = "लाईट थीम",
                darkTheme = "डार्क थीम",
                primaryContact = "मुख्य संपर्क",
                policeEmergency = "पोलीस हेल्पलाइन (११२)",
                mapDirections = "गुगल मॅप्सवर पहा",
                callDirectly = "थेट कॉल करा"
            )

            AppLanguage.TAMIL -> LocalizedStrings(
                appTitle = "ஹெர்ஷீல்ட் (HerShield)",
                appSubtitle = "பெண்கள் பாதுகாப்பு & அவசர எஸ்.ஓ.எஸ்",
                oneTapHelp = "ஒரே தட்டலில் உதவி",
                tapToTriggerSos = "எஸ்.ஓ.எஸ் அனுப்ப தட்டவும்",
                emergencyActive = "அவசர நிலை தீவிரமானது",
                resolveSos = "நான் பாதுகாப்பாக உள்ளேன் (ரத்துசெய்)",
                emergencySiren = "அவசர சைரன்",
                sirenActive = "சைரன் ஒலிக்கிறது",
                testSilentSos = "அமைதியான எஸ்.ஓ.எஸ்",
                liveGpsActive = "நேரலை ஜி.பி.எஸ் கண்காணிப்பு செயலில் உள்ளது",
                gpsStandby = "ஜி.பி.எஸ் தயார்",
                instantSharedBanner = "முதன்மை தொடர்புக்கு கூகுள் மேப்ஸ் இருப்பிடம் உடனடியாக பகிரப்பட்டது!",
                daisyChainTitle = "தொடர் அவசர அழைப்பு சங்கிலி",
                daisyChainSubtitle = "யாராவது எடுக்கும் வரை வரிசையாக அழைப்பு",
                startChain = "அழைப்பைத் தொடங்கு",
                cycle = "சுற்று",
                answeredConnected = "இணைக்கப்பட்டது",
                escalateNext = "அடுத்தவருக்கு அழை",
                oneMinAudioTitle = "1-நிமிட ஆடியோ பாதுகாப்பு பதிவு",
                audioRecording = "ஆடியோ பதிவாகிறது...",
                analyzeNow = "இப்போதே ஆய்வு செய்",
                aiSituationTitle = "ஏஐ பாதுகாப்பு நிலை ஆய்வாளர்",
                aiAssistantTab = "அஸ்ட்ரா ஏஐ உதவியாளர்",
                askAssistantPlaceholder = "பாதுகாப்பு பற்றி எதையும் கேட்கலாம்...",
                sendQuery = "அனுப்பு",
                dashboardTab = "டாஷ்போர்டு",
                sosTab = "எஸ்.ஓ.எஸ்",
                contactsTab = "தொடர்புகள்",
                profileTab = "சுயவிவரம்",
                selectLanguage = "மொழியைத் தேர்ந்தெடுக்கவும்",
                themeMode = "தீம் மாற்று",
                lightTheme = "லைட் தீம்",
                darkTheme = "டார்க் தீம்",
                primaryContact = "முதன்மை தொடர்பு",
                policeEmergency = "காவல்துறை (112)",
                mapDirections = "கூகுள் மேப்பில் பார்க்க",
                callDirectly = "நேரடி அழைப்பு"
            )

            else -> LocalizedStrings(
                appTitle = "HerShield",
                appSubtitle = "AI-Powered Women Safety & Instant Emergency SOS",
                oneTapHelp = "One-Tap Help",
                tapToTriggerSos = "TAP TO TRIGGER SOS",
                emergencyActive = "EMERGENCY SOS ACTIVE",
                resolveSos = "I'm Safe Now (Resolve Alert)",
                emergencySiren = "Emergency Siren",
                sirenActive = "Siren Blaring",
                testSilentSos = "Test Silent SOS",
                liveGpsActive = "REAL-TIME GPS TRACKING ACTIVE",
                gpsStandby = "GPS STANDBY",
                instantSharedBanner = "Live Google Maps location instantly shared with Primary Contact!",
                daisyChainTitle = "Emergency Calling Daisy Chain",
                daisyChainSubtitle = "Sequential auto-calling till someone answers",
                startChain = "Start Chain",
                cycle = "Cycle",
                answeredConnected = "Answered",
                escalateNext = "Escalate Next",
                oneMinAudioTitle = "1-Minute Security Audio Recording",
                audioRecording = "Audio recording in progress...",
                analyzeNow = "Analyze Now",
                aiSituationTitle = "AI Situation Threat Classifier",
                aiAssistantTab = "Astra AI Safety Assistant",
                askAssistantPlaceholder = "Ask anything about your safety, travel, or danger protocols...",
                sendQuery = "Send",
                dashboardTab = "Dashboard",
                sosTab = "SOS",
                contactsTab = "Contacts",
                profileTab = "Profile",
                selectLanguage = "Choose Language",
                themeMode = "App Theme Mode",
                lightTheme = "Light Theme",
                darkTheme = "Dark Theme",
                primaryContact = "Primary Contact",
                policeEmergency = "Police Dispatch (112)",
                mapDirections = "Open in Google Maps",
                callDirectly = "Call Directly"
            )
        }
    }
}
